// Generated by jextract

package com.sun.security.auth.module.unix.pwd;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$0 {

    static final FunctionDescriptor getpwuid_r$FUNC = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        ADDRESS,
        ADDRESS,
        JAVA_LONG,
        ADDRESS
    );
    static final MethodHandle getpwuid_r$MH = RuntimeHelper.downcallHandle(
        "getpwuid_r",
        constants$0.getpwuid_r$FUNC, false
    );
}


