// Generated by jextract

package com.sun.security.auth.module.unix.pwd;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class pwd_h  {

    /* package-private */ pwd_h() {}
    public static ValueLayout.OfByte C_CHAR = JAVA_BYTE;
    public static ValueLayout.OfShort C_SHORT = JAVA_SHORT;
    public static ValueLayout.OfInt C_INT = JAVA_INT;
    public static ValueLayout.OfLong C_LONG = JAVA_LONG;
    public static ValueLayout.OfLong C_LONG_LONG = JAVA_LONG;
    public static ValueLayout.OfFloat C_FLOAT = JAVA_FLOAT;
    public static ValueLayout.OfDouble C_DOUBLE = JAVA_DOUBLE;
    public static ValueLayout.OfAddress C_POINTER = ValueLayout.ADDRESS;
    public static MethodHandle getpwuid_r$MH() {
        return RuntimeHelper.requireNonNull(constants$0.getpwuid_r$MH,"getpwuid_r");
    }
    public static int getpwuid_r ( int x0,  Addressable x1,  Addressable x2,  long x3,  Addressable x4) {
        var mh$ = RuntimeHelper.requireNonNull(constants$0.getpwuid_r$MH, "getpwuid_r");
        try {
            return (int)mh$.invokeExact(x0, x1, x2, x3, x4);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}


