// Generated by jextract

package com.sun.security.auth.module.unix.unistd;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$0 {

    static final FunctionDescriptor getgid$FUNC = FunctionDescriptor.of(JAVA_INT);
    static final MethodHandle getgid$MH = RuntimeHelper.downcallHandle(
        "getgid",
        constants$0.getgid$FUNC, false
    );
    static final FunctionDescriptor getgroups$FUNC = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        ADDRESS
    );
    static final MethodHandle getgroups$MH = RuntimeHelper.downcallHandle(
        "getgroups",
        constants$0.getgroups$FUNC, false
    );
    static final FunctionDescriptor getuid$FUNC = FunctionDescriptor.of(JAVA_INT);
    static final MethodHandle getuid$MH = RuntimeHelper.downcallHandle(
        "getuid",
        constants$0.getuid$FUNC, false
    );
}


