// Generated by jextract

package com.sun.security.auth.module.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$2 {

    static final FunctionDescriptor GetSidIdentifierAuthority$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle GetSidIdentifierAuthority$MH = RuntimeHelper.downcallHandle(
        "GetSidIdentifierAuthority",
        constants$2.GetSidIdentifierAuthority$FUNC, false
    );
    static final FunctionDescriptor GetSidSubAuthority$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        JAVA_INT
    );
    static final MethodHandle GetSidSubAuthority$MH = RuntimeHelper.downcallHandle(
        "GetSidSubAuthority",
        constants$2.GetSidSubAuthority$FUNC, false
    );
    static final FunctionDescriptor GetSidSubAuthorityCount$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle GetSidSubAuthorityCount$MH = RuntimeHelper.downcallHandle(
        "GetSidSubAuthorityCount",
        constants$2.GetSidSubAuthorityCount$FUNC, false
    );
    static final FunctionDescriptor GetTokenInformation$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        JAVA_INT,
        ADDRESS,
        JAVA_INT,
        ADDRESS
    );
    static final MethodHandle GetTokenInformation$MH = RuntimeHelper.downcallHandle(
        "GetTokenInformation",
        constants$2.GetTokenInformation$FUNC, false
    );
    static final FunctionDescriptor IsValidSid$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS
    );
    static final MethodHandle IsValidSid$MH = RuntimeHelper.downcallHandle(
        "IsValidSid",
        constants$2.IsValidSid$FUNC, false
    );
    static final FunctionDescriptor LocalFree$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS
    );
    static final MethodHandle LocalFree$MH = RuntimeHelper.downcallHandle(
        "LocalFree",
        constants$2.LocalFree$FUNC, false
    );
}


