// Generated by jextract

package com.sun.security.auth.module.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$3 {

    static final FunctionDescriptor FormatMessageA$FUNC = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        ADDRESS,
        JAVA_INT,
        JAVA_INT,
        ADDRESS,
        JAVA_INT,
        ADDRESS
    );
    static final MethodHandle FormatMessageA$MH = RuntimeHelper.downcallHandle(
        "FormatMessageA",
        constants$3.FormatMessageA$FUNC, false
    );
    static final FunctionDescriptor LookupAccountSidA$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle LookupAccountSidA$MH = RuntimeHelper.downcallHandle(
        "LookupAccountSidA",
        constants$3.LookupAccountSidA$FUNC, false
    );
    static final FunctionDescriptor LookupAccountNameA$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle LookupAccountNameA$MH = RuntimeHelper.downcallHandle(
        "LookupAccountNameA",
        constants$3.LookupAccountNameA$FUNC, false
    );
    static final MemoryAddress INVALID_HANDLE_VALUE$ADDR = MemoryAddress.ofLong(-1L);
}


